version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
    reviewers:
      - mark-j
    assignees:
      - marks-ci-bot
